services:
  backend:
    build: ./src
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "8080:80"

  db:
    image: postgres:13
    restart: always
    hostname: db
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2
    restart: always
    hostname: redis
    mem_limit: 256mb
    command: ["redis-server", "--maxmemory-policy", "allkeys-lru"]

  nginx:
    build: ./proxy
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

volumes:
  db_data:


