name: Test Website Build
on:
  push:
    branches: [master]


jobs: 
  build-website-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Copies Code in
        uses: actions/checkout@v5

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
              echo BACKEND_SITE_URL=${{ secrets.BACKEND_SITE_URL }} >> .env
              echo FRONTEND_SITE_URL=${{ secrets.FRONTEND_SITE_URL }} >> .env
              echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
              echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
              echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
              echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
              echo SECRET_SESSION_KEY=${{ secrets.SECRET_SESSION_KEY }} >> .env

      - name: Build  Docker Containers
        run: docker compose build


